/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: ipc.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "ipc.pb-c.h"
void   auth_cookie_request_msg__init
                     (AuthCookieRequestMsg         *message)
{
  static AuthCookieRequestMsg init_value = AUTH_COOKIE_REQUEST_MSG__INIT;
  *message = init_value;
}
size_t auth_cookie_request_msg__get_packed_size
                     (const AuthCookieRequestMsg *message)
{
  assert(message->base.descriptor == &auth_cookie_request_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t auth_cookie_request_msg__pack
                     (const AuthCookieRequestMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &auth_cookie_request_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t auth_cookie_request_msg__pack_to_buffer
                     (const AuthCookieRequestMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &auth_cookie_request_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
AuthCookieRequestMsg *
       auth_cookie_request_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (AuthCookieRequestMsg *)
     protobuf_c_message_unpack (&auth_cookie_request_msg__descriptor,
                                allocator, len, data);
}
void   auth_cookie_request_msg__free_unpacked
                     (AuthCookieRequestMsg *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &auth_cookie_request_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   auth_reply_msg__init
                     (AuthReplyMsg         *message)
{
  static AuthReplyMsg init_value = AUTH_REPLY_MSG__INIT;
  *message = init_value;
}
size_t auth_reply_msg__get_packed_size
                     (const AuthReplyMsg *message)
{
  assert(message->base.descriptor == &auth_reply_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t auth_reply_msg__pack
                     (const AuthReplyMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &auth_reply_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t auth_reply_msg__pack_to_buffer
                     (const AuthReplyMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &auth_reply_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
AuthReplyMsg *
       auth_reply_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (AuthReplyMsg *)
     protobuf_c_message_unpack (&auth_reply_msg__descriptor,
                                allocator, len, data);
}
void   auth_reply_msg__free_unpacked
                     (AuthReplyMsg *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &auth_reply_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   session_resume_fetch_msg__init
                     (SessionResumeFetchMsg         *message)
{
  static SessionResumeFetchMsg init_value = SESSION_RESUME_FETCH_MSG__INIT;
  *message = init_value;
}
size_t session_resume_fetch_msg__get_packed_size
                     (const SessionResumeFetchMsg *message)
{
  assert(message->base.descriptor == &session_resume_fetch_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t session_resume_fetch_msg__pack
                     (const SessionResumeFetchMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &session_resume_fetch_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t session_resume_fetch_msg__pack_to_buffer
                     (const SessionResumeFetchMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &session_resume_fetch_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SessionResumeFetchMsg *
       session_resume_fetch_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SessionResumeFetchMsg *)
     protobuf_c_message_unpack (&session_resume_fetch_msg__descriptor,
                                allocator, len, data);
}
void   session_resume_fetch_msg__free_unpacked
                     (SessionResumeFetchMsg *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &session_resume_fetch_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   session_resume_store_req_msg__init
                     (SessionResumeStoreReqMsg         *message)
{
  static SessionResumeStoreReqMsg init_value = SESSION_RESUME_STORE_REQ_MSG__INIT;
  *message = init_value;
}
size_t session_resume_store_req_msg__get_packed_size
                     (const SessionResumeStoreReqMsg *message)
{
  assert(message->base.descriptor == &session_resume_store_req_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t session_resume_store_req_msg__pack
                     (const SessionResumeStoreReqMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &session_resume_store_req_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t session_resume_store_req_msg__pack_to_buffer
                     (const SessionResumeStoreReqMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &session_resume_store_req_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SessionResumeStoreReqMsg *
       session_resume_store_req_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SessionResumeStoreReqMsg *)
     protobuf_c_message_unpack (&session_resume_store_req_msg__descriptor,
                                allocator, len, data);
}
void   session_resume_store_req_msg__free_unpacked
                     (SessionResumeStoreReqMsg *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &session_resume_store_req_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   session_resume_reply_msg__init
                     (SessionResumeReplyMsg         *message)
{
  static SessionResumeReplyMsg init_value = SESSION_RESUME_REPLY_MSG__INIT;
  *message = init_value;
}
size_t session_resume_reply_msg__get_packed_size
                     (const SessionResumeReplyMsg *message)
{
  assert(message->base.descriptor == &session_resume_reply_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t session_resume_reply_msg__pack
                     (const SessionResumeReplyMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &session_resume_reply_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t session_resume_reply_msg__pack_to_buffer
                     (const SessionResumeReplyMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &session_resume_reply_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SessionResumeReplyMsg *
       session_resume_reply_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SessionResumeReplyMsg *)
     protobuf_c_message_unpack (&session_resume_reply_msg__descriptor,
                                allocator, len, data);
}
void   session_resume_reply_msg__free_unpacked
                     (SessionResumeReplyMsg *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &session_resume_reply_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   tun_mtu_msg__init
                     (TunMtuMsg         *message)
{
  static TunMtuMsg init_value = TUN_MTU_MSG__INIT;
  *message = init_value;
}
size_t tun_mtu_msg__get_packed_size
                     (const TunMtuMsg *message)
{
  assert(message->base.descriptor == &tun_mtu_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t tun_mtu_msg__pack
                     (const TunMtuMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &tun_mtu_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t tun_mtu_msg__pack_to_buffer
                     (const TunMtuMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &tun_mtu_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TunMtuMsg *
       tun_mtu_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TunMtuMsg *)
     protobuf_c_message_unpack (&tun_mtu_msg__descriptor,
                                allocator, len, data);
}
void   tun_mtu_msg__free_unpacked
                     (TunMtuMsg *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &tun_mtu_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   cli_stats_msg__init
                     (CliStatsMsg         *message)
{
  static CliStatsMsg init_value = CLI_STATS_MSG__INIT;
  *message = init_value;
}
size_t cli_stats_msg__get_packed_size
                     (const CliStatsMsg *message)
{
  assert(message->base.descriptor == &cli_stats_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cli_stats_msg__pack
                     (const CliStatsMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &cli_stats_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cli_stats_msg__pack_to_buffer
                     (const CliStatsMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &cli_stats_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CliStatsMsg *
       cli_stats_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CliStatsMsg *)
     protobuf_c_message_unpack (&cli_stats_msg__descriptor,
                                allocator, len, data);
}
void   cli_stats_msg__free_unpacked
                     (CliStatsMsg *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &cli_stats_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   udp_fd_msg__init
                     (UdpFdMsg         *message)
{
  static UdpFdMsg init_value = UDP_FD_MSG__INIT;
  *message = init_value;
}
size_t udp_fd_msg__get_packed_size
                     (const UdpFdMsg *message)
{
  assert(message->base.descriptor == &udp_fd_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t udp_fd_msg__pack
                     (const UdpFdMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &udp_fd_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t udp_fd_msg__pack_to_buffer
                     (const UdpFdMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &udp_fd_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
UdpFdMsg *
       udp_fd_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (UdpFdMsg *)
     protobuf_c_message_unpack (&udp_fd_msg__descriptor,
                                allocator, len, data);
}
void   udp_fd_msg__free_unpacked
                     (UdpFdMsg *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &udp_fd_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   session_info_msg__init
                     (SessionInfoMsg         *message)
{
  static SessionInfoMsg init_value = SESSION_INFO_MSG__INIT;
  *message = init_value;
}
size_t session_info_msg__get_packed_size
                     (const SessionInfoMsg *message)
{
  assert(message->base.descriptor == &session_info_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t session_info_msg__pack
                     (const SessionInfoMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &session_info_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t session_info_msg__pack_to_buffer
                     (const SessionInfoMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &session_info_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SessionInfoMsg *
       session_info_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SessionInfoMsg *)
     protobuf_c_message_unpack (&session_info_msg__descriptor,
                                allocator, len, data);
}
void   session_info_msg__free_unpacked
                     (SessionInfoMsg *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &session_info_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ban_ip_msg__init
                     (BanIpMsg         *message)
{
  static BanIpMsg init_value = BAN_IP_MSG__INIT;
  *message = init_value;
}
size_t ban_ip_msg__get_packed_size
                     (const BanIpMsg *message)
{
  assert(message->base.descriptor == &ban_ip_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ban_ip_msg__pack
                     (const BanIpMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ban_ip_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ban_ip_msg__pack_to_buffer
                     (const BanIpMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ban_ip_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
BanIpMsg *
       ban_ip_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (BanIpMsg *)
     protobuf_c_message_unpack (&ban_ip_msg__descriptor,
                                allocator, len, data);
}
void   ban_ip_msg__free_unpacked
                     (BanIpMsg *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &ban_ip_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ban_ip_reply_msg__init
                     (BanIpReplyMsg         *message)
{
  static BanIpReplyMsg init_value = BAN_IP_REPLY_MSG__INIT;
  *message = init_value;
}
size_t ban_ip_reply_msg__get_packed_size
                     (const BanIpReplyMsg *message)
{
  assert(message->base.descriptor == &ban_ip_reply_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ban_ip_reply_msg__pack
                     (const BanIpReplyMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ban_ip_reply_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ban_ip_reply_msg__pack_to_buffer
                     (const BanIpReplyMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ban_ip_reply_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
BanIpReplyMsg *
       ban_ip_reply_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (BanIpReplyMsg *)
     protobuf_c_message_unpack (&ban_ip_reply_msg__descriptor,
                                allocator, len, data);
}
void   ban_ip_reply_msg__free_unpacked
                     (BanIpReplyMsg *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &ban_ip_reply_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sec_auth_init_msg__init
                     (SecAuthInitMsg         *message)
{
  static SecAuthInitMsg init_value = SEC_AUTH_INIT_MSG__INIT;
  *message = init_value;
}
size_t sec_auth_init_msg__get_packed_size
                     (const SecAuthInitMsg *message)
{
  assert(message->base.descriptor == &sec_auth_init_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sec_auth_init_msg__pack
                     (const SecAuthInitMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sec_auth_init_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sec_auth_init_msg__pack_to_buffer
                     (const SecAuthInitMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sec_auth_init_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SecAuthInitMsg *
       sec_auth_init_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SecAuthInitMsg *)
     protobuf_c_message_unpack (&sec_auth_init_msg__descriptor,
                                allocator, len, data);
}
void   sec_auth_init_msg__free_unpacked
                     (SecAuthInitMsg *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &sec_auth_init_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sec_auth_cont_msg__init
                     (SecAuthContMsg         *message)
{
  static SecAuthContMsg init_value = SEC_AUTH_CONT_MSG__INIT;
  *message = init_value;
}
size_t sec_auth_cont_msg__get_packed_size
                     (const SecAuthContMsg *message)
{
  assert(message->base.descriptor == &sec_auth_cont_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sec_auth_cont_msg__pack
                     (const SecAuthContMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sec_auth_cont_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sec_auth_cont_msg__pack_to_buffer
                     (const SecAuthContMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sec_auth_cont_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SecAuthContMsg *
       sec_auth_cont_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SecAuthContMsg *)
     protobuf_c_message_unpack (&sec_auth_cont_msg__descriptor,
                                allocator, len, data);
}
void   sec_auth_cont_msg__free_unpacked
                     (SecAuthContMsg *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &sec_auth_cont_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sec_auth_reply_msg__init
                     (SecAuthReplyMsg         *message)
{
  static SecAuthReplyMsg init_value = SEC_AUTH_REPLY_MSG__INIT;
  *message = init_value;
}
size_t sec_auth_reply_msg__get_packed_size
                     (const SecAuthReplyMsg *message)
{
  assert(message->base.descriptor == &sec_auth_reply_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sec_auth_reply_msg__pack
                     (const SecAuthReplyMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sec_auth_reply_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sec_auth_reply_msg__pack_to_buffer
                     (const SecAuthReplyMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sec_auth_reply_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SecAuthReplyMsg *
       sec_auth_reply_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SecAuthReplyMsg *)
     protobuf_c_message_unpack (&sec_auth_reply_msg__descriptor,
                                allocator, len, data);
}
void   sec_auth_reply_msg__free_unpacked
                     (SecAuthReplyMsg *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &sec_auth_reply_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sec_op_msg__init
                     (SecOpMsg         *message)
{
  static SecOpMsg init_value = SEC_OP_MSG__INIT;
  *message = init_value;
}
size_t sec_op_msg__get_packed_size
                     (const SecOpMsg *message)
{
  assert(message->base.descriptor == &sec_op_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sec_op_msg__pack
                     (const SecOpMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sec_op_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sec_op_msg__pack_to_buffer
                     (const SecOpMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sec_op_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SecOpMsg *
       sec_op_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SecOpMsg *)
     protobuf_c_message_unpack (&sec_op_msg__descriptor,
                                allocator, len, data);
}
void   sec_op_msg__free_unpacked
                     (SecOpMsg *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &sec_op_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   cookie__init
                     (Cookie         *message)
{
  static Cookie init_value = COOKIE__INIT;
  *message = init_value;
}
size_t cookie__get_packed_size
                     (const Cookie *message)
{
  assert(message->base.descriptor == &cookie__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cookie__pack
                     (const Cookie *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &cookie__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cookie__pack_to_buffer
                     (const Cookie *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &cookie__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Cookie *
       cookie__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Cookie *)
     protobuf_c_message_unpack (&cookie__descriptor,
                                allocator, len, data);
}
void   cookie__free_unpacked
                     (Cookie *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &cookie__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sec_auth_session_msg__init
                     (SecAuthSessionMsg         *message)
{
  static SecAuthSessionMsg init_value = SEC_AUTH_SESSION_MSG__INIT;
  *message = init_value;
}
size_t sec_auth_session_msg__get_packed_size
                     (const SecAuthSessionMsg *message)
{
  assert(message->base.descriptor == &sec_auth_session_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sec_auth_session_msg__pack
                     (const SecAuthSessionMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sec_auth_session_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sec_auth_session_msg__pack_to_buffer
                     (const SecAuthSessionMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sec_auth_session_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SecAuthSessionMsg *
       sec_auth_session_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SecAuthSessionMsg *)
     protobuf_c_message_unpack (&sec_auth_session_msg__descriptor,
                                allocator, len, data);
}
void   sec_auth_session_msg__free_unpacked
                     (SecAuthSessionMsg *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &sec_auth_session_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sec_auth_session_reply_msg__init
                     (SecAuthSessionReplyMsg         *message)
{
  static SecAuthSessionReplyMsg init_value = SEC_AUTH_SESSION_REPLY_MSG__INIT;
  *message = init_value;
}
size_t sec_auth_session_reply_msg__get_packed_size
                     (const SecAuthSessionReplyMsg *message)
{
  assert(message->base.descriptor == &sec_auth_session_reply_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sec_auth_session_reply_msg__pack
                     (const SecAuthSessionReplyMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sec_auth_session_reply_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sec_auth_session_reply_msg__pack_to_buffer
                     (const SecAuthSessionReplyMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sec_auth_session_reply_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SecAuthSessionReplyMsg *
       sec_auth_session_reply_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SecAuthSessionReplyMsg *)
     protobuf_c_message_unpack (&sec_auth_session_reply_msg__descriptor,
                                allocator, len, data);
}
void   sec_auth_session_reply_msg__free_unpacked
                     (SecAuthSessionReplyMsg *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &sec_auth_session_reply_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor auth_cookie_request_msg__field_descriptors[1] =
{
  {
    "cookie",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(AuthCookieRequestMsg, cookie),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned auth_cookie_request_msg__field_indices_by_name[] = {
  0,   /* field[0] = cookie */
};
static const ProtobufCIntRange auth_cookie_request_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor auth_cookie_request_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "auth_cookie_request_msg",
  "AuthCookieRequestMsg",
  "AuthCookieRequestMsg",
  "",
  sizeof(AuthCookieRequestMsg),
  1,
  auth_cookie_request_msg__field_descriptors,
  auth_cookie_request_msg__field_indices_by_name,
  1,  auth_cookie_request_msg__number_ranges,
  (ProtobufCMessageInit) auth_cookie_request_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const protobuf_c_boolean auth_reply_msg__no_udp__default_value = 0;
static const ProtobufCFieldDescriptor auth_reply_msg__field_descriptors[24] =
{
  {
    "reply",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(AuthReplyMsg, reply),
    &auth__rep__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "session_id",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(AuthReplyMsg, has_session_id),
    offsetof(AuthReplyMsg, session_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vname",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(AuthReplyMsg, vname),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "user_name",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(AuthReplyMsg, user_name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "msg",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(AuthReplyMsg, msg),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ipv4",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(AuthReplyMsg, ipv4),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ipv6",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(AuthReplyMsg, ipv6),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ipv4_local",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(AuthReplyMsg, ipv4_local),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ipv6_local",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(AuthReplyMsg, ipv6_local),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ipv4_netmask",
    15,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(AuthReplyMsg, ipv4_netmask),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ipv6_netmask",
    16,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(AuthReplyMsg, ipv6_netmask),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ipv6_prefix",
    17,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(AuthReplyMsg, has_ipv6_prefix),
    offsetof(AuthReplyMsg, ipv6_prefix),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rx_per_sec",
    18,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(AuthReplyMsg, has_rx_per_sec),
    offsetof(AuthReplyMsg, rx_per_sec),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tx_per_sec",
    19,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(AuthReplyMsg, has_tx_per_sec),
    offsetof(AuthReplyMsg, tx_per_sec),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "net_priority",
    20,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(AuthReplyMsg, has_net_priority),
    offsetof(AuthReplyMsg, net_priority),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "routes",
    21,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(AuthReplyMsg, n_routes),
    offsetof(AuthReplyMsg, routes),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dns",
    22,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(AuthReplyMsg, n_dns),
    offsetof(AuthReplyMsg, dns),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nbns",
    23,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(AuthReplyMsg, n_nbns),
    offsetof(AuthReplyMsg, nbns),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "no_udp",
    24,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(AuthReplyMsg, has_no_udp),
    offsetof(AuthReplyMsg, no_udp),
    NULL,
    &auth_reply_msg__no_udp__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "group_name",
    25,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(AuthReplyMsg, group_name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "xml_config_file",
    26,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(AuthReplyMsg, xml_config_file),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ipv4_network",
    27,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(AuthReplyMsg, ipv4_network),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ipv6_network",
    28,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(AuthReplyMsg, ipv6_network),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "no_routes",
    29,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(AuthReplyMsg, n_no_routes),
    offsetof(AuthReplyMsg, no_routes),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned auth_reply_msg__field_indices_by_name[] = {
  16,   /* field[16] = dns */
  19,   /* field[19] = group_name */
  5,   /* field[5] = ipv4 */
  7,   /* field[7] = ipv4_local */
  9,   /* field[9] = ipv4_netmask */
  21,   /* field[21] = ipv4_network */
  6,   /* field[6] = ipv6 */
  8,   /* field[8] = ipv6_local */
  10,   /* field[10] = ipv6_netmask */
  22,   /* field[22] = ipv6_network */
  11,   /* field[11] = ipv6_prefix */
  4,   /* field[4] = msg */
  17,   /* field[17] = nbns */
  14,   /* field[14] = net_priority */
  23,   /* field[23] = no_routes */
  18,   /* field[18] = no_udp */
  0,   /* field[0] = reply */
  15,   /* field[15] = routes */
  12,   /* field[12] = rx_per_sec */
  1,   /* field[1] = session_id */
  13,   /* field[13] = tx_per_sec */
  3,   /* field[3] = user_name */
  2,   /* field[2] = vname */
  20,   /* field[20] = xml_config_file */
};
static const ProtobufCIntRange auth_reply_msg__number_ranges[3 + 1] =
{
  { 1, 0 },
  { 3, 1 },
  { 15, 9 },
  { 0, 24 }
};
const ProtobufCMessageDescriptor auth_reply_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "auth_reply_msg",
  "AuthReplyMsg",
  "AuthReplyMsg",
  "",
  sizeof(AuthReplyMsg),
  24,
  auth_reply_msg__field_descriptors,
  auth_reply_msg__field_indices_by_name,
  3,  auth_reply_msg__number_ranges,
  (ProtobufCMessageInit) auth_reply_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor session_resume_fetch_msg__field_descriptors[1] =
{
  {
    "session_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(SessionResumeFetchMsg, session_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned session_resume_fetch_msg__field_indices_by_name[] = {
  0,   /* field[0] = session_id */
};
static const ProtobufCIntRange session_resume_fetch_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor session_resume_fetch_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "session_resume_fetch_msg",
  "SessionResumeFetchMsg",
  "SessionResumeFetchMsg",
  "",
  sizeof(SessionResumeFetchMsg),
  1,
  session_resume_fetch_msg__field_descriptors,
  session_resume_fetch_msg__field_indices_by_name,
  1,  session_resume_fetch_msg__number_ranges,
  (ProtobufCMessageInit) session_resume_fetch_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor session_resume_store_req_msg__field_descriptors[2] =
{
  {
    "session_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(SessionResumeStoreReqMsg, session_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "session_data",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(SessionResumeStoreReqMsg, session_data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned session_resume_store_req_msg__field_indices_by_name[] = {
  1,   /* field[1] = session_data */
  0,   /* field[0] = session_id */
};
static const ProtobufCIntRange session_resume_store_req_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor session_resume_store_req_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "session_resume_store_req_msg",
  "SessionResumeStoreReqMsg",
  "SessionResumeStoreReqMsg",
  "",
  sizeof(SessionResumeStoreReqMsg),
  2,
  session_resume_store_req_msg__field_descriptors,
  session_resume_store_req_msg__field_indices_by_name,
  1,  session_resume_store_req_msg__number_ranges,
  (ProtobufCMessageInit) session_resume_store_req_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
const ProtobufCEnumValue session_resume_reply_msg__resume__rep__enum_values_by_number[2] =
{
  { "OK", "SESSION_RESUME_REPLY_MSG__RESUME__REP__OK", 1 },
  { "FAILED", "SESSION_RESUME_REPLY_MSG__RESUME__REP__FAILED", 2 },
};
static const ProtobufCIntRange session_resume_reply_msg__resume__rep__value_ranges[] = {
{1, 0},{0, 2}
};
const ProtobufCEnumValueIndex session_resume_reply_msg__resume__rep__enum_values_by_name[2] =
{
  { "FAILED", 1 },
  { "OK", 0 },
};
const ProtobufCEnumDescriptor session_resume_reply_msg__resume__rep__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "session_resume_reply_msg.RESUME_REP",
  "RESUME_REP",
  "SessionResumeReplyMsg__RESUMEREP",
  "",
  2,
  session_resume_reply_msg__resume__rep__enum_values_by_number,
  2,
  session_resume_reply_msg__resume__rep__enum_values_by_name,
  1,
  session_resume_reply_msg__resume__rep__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor session_resume_reply_msg__field_descriptors[2] =
{
  {
    "reply",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(SessionResumeReplyMsg, reply),
    &session_resume_reply_msg__resume__rep__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "session_data",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(SessionResumeReplyMsg, has_session_data),
    offsetof(SessionResumeReplyMsg, session_data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned session_resume_reply_msg__field_indices_by_name[] = {
  0,   /* field[0] = reply */
  1,   /* field[1] = session_data */
};
static const ProtobufCIntRange session_resume_reply_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor session_resume_reply_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "session_resume_reply_msg",
  "SessionResumeReplyMsg",
  "SessionResumeReplyMsg",
  "",
  sizeof(SessionResumeReplyMsg),
  2,
  session_resume_reply_msg__field_descriptors,
  session_resume_reply_msg__field_indices_by_name,
  1,  session_resume_reply_msg__number_ranges,
  (ProtobufCMessageInit) session_resume_reply_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor tun_mtu_msg__field_descriptors[1] =
{
  {
    "mtu",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(TunMtuMsg, mtu),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned tun_mtu_msg__field_indices_by_name[] = {
  0,   /* field[0] = mtu */
};
static const ProtobufCIntRange tun_mtu_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor tun_mtu_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "tun_mtu_msg",
  "TunMtuMsg",
  "TunMtuMsg",
  "",
  sizeof(TunMtuMsg),
  1,
  tun_mtu_msg__field_descriptors,
  tun_mtu_msg__field_indices_by_name,
  1,  tun_mtu_msg__number_ranges,
  (ProtobufCMessageInit) tun_mtu_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor cli_stats_msg__field_descriptors[7] =
{
  {
    "bytes_in",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(CliStatsMsg, bytes_in),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bytes_out",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(CliStatsMsg, bytes_out),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sid",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(CliStatsMsg, has_sid),
    offsetof(CliStatsMsg, sid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "uptime",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(CliStatsMsg, uptime),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "remote_ip",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(CliStatsMsg, remote_ip),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ipv4",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(CliStatsMsg, ipv4),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ipv6",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(CliStatsMsg, ipv6),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cli_stats_msg__field_indices_by_name[] = {
  0,   /* field[0] = bytes_in */
  1,   /* field[1] = bytes_out */
  5,   /* field[5] = ipv4 */
  6,   /* field[6] = ipv6 */
  4,   /* field[4] = remote_ip */
  2,   /* field[2] = sid */
  3,   /* field[3] = uptime */
};
static const ProtobufCIntRange cli_stats_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor cli_stats_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "cli_stats_msg",
  "CliStatsMsg",
  "CliStatsMsg",
  "",
  sizeof(CliStatsMsg),
  7,
  cli_stats_msg__field_descriptors,
  cli_stats_msg__field_indices_by_name,
  1,  cli_stats_msg__number_ranges,
  (ProtobufCMessageInit) cli_stats_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const protobuf_c_boolean udp_fd_msg__hello__default_value = 1;
static const ProtobufCFieldDescriptor udp_fd_msg__field_descriptors[2] =
{
  {
    "hello",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(UdpFdMsg, hello),
    NULL,
    &udp_fd_msg__hello__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(UdpFdMsg, has_data),
    offsetof(UdpFdMsg, data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned udp_fd_msg__field_indices_by_name[] = {
  1,   /* field[1] = data */
  0,   /* field[0] = hello */
};
static const ProtobufCIntRange udp_fd_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor udp_fd_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "udp_fd_msg",
  "UdpFdMsg",
  "UdpFdMsg",
  "",
  sizeof(UdpFdMsg),
  2,
  udp_fd_msg__field_descriptors,
  udp_fd_msg__field_indices_by_name,
  1,  udp_fd_msg__number_ranges,
  (ProtobufCMessageInit) udp_fd_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor session_info_msg__field_descriptors[5] =
{
  {
    "tls_ciphersuite",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SessionInfoMsg, tls_ciphersuite),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dtls_ciphersuite",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SessionInfoMsg, dtls_ciphersuite),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "user_agent",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SessionInfoMsg, user_agent),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cstp_compr",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SessionInfoMsg, cstp_compr),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dtls_compr",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SessionInfoMsg, dtls_compr),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned session_info_msg__field_indices_by_name[] = {
  3,   /* field[3] = cstp_compr */
  1,   /* field[1] = dtls_ciphersuite */
  4,   /* field[4] = dtls_compr */
  0,   /* field[0] = tls_ciphersuite */
  2,   /* field[2] = user_agent */
};
static const ProtobufCIntRange session_info_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor session_info_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "session_info_msg",
  "SessionInfoMsg",
  "SessionInfoMsg",
  "",
  sizeof(SessionInfoMsg),
  5,
  session_info_msg__field_descriptors,
  session_info_msg__field_indices_by_name,
  1,  session_info_msg__number_ranges,
  (ProtobufCMessageInit) session_info_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ban_ip_msg__field_descriptors[2] =
{
  {
    "ip",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(BanIpMsg, ip),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "score",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(BanIpMsg, score),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ban_ip_msg__field_indices_by_name[] = {
  0,   /* field[0] = ip */
  1,   /* field[1] = score */
};
static const ProtobufCIntRange ban_ip_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor ban_ip_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ban_ip_msg",
  "BanIpMsg",
  "BanIpMsg",
  "",
  sizeof(BanIpMsg),
  2,
  ban_ip_msg__field_descriptors,
  ban_ip_msg__field_indices_by_name,
  1,  ban_ip_msg__number_ranges,
  (ProtobufCMessageInit) ban_ip_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ban_ip_reply_msg__field_descriptors[1] =
{
  {
    "reply",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(BanIpReplyMsg, reply),
    &auth__rep__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ban_ip_reply_msg__field_indices_by_name[] = {
  0,   /* field[0] = reply */
};
static const ProtobufCIntRange ban_ip_reply_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor ban_ip_reply_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ban_ip_reply_msg",
  "BanIpReplyMsg",
  "BanIpReplyMsg",
  "",
  sizeof(BanIpReplyMsg),
  1,
  ban_ip_reply_msg__field_descriptors,
  ban_ip_reply_msg__field_indices_by_name,
  1,  ban_ip_reply_msg__number_ranges,
  (ProtobufCMessageInit) ban_ip_reply_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const protobuf_c_boolean sec_auth_init_msg__tls_auth_ok__default_value = 0;
static const uint32_t sec_auth_init_msg__auth_type__default_value = 0u;
static const ProtobufCFieldDescriptor sec_auth_init_msg__field_descriptors[8] =
{
  {
    "tls_auth_ok",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(SecAuthInitMsg, tls_auth_ok),
    NULL,
    &sec_auth_init_msg__tls_auth_ok__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "user_name",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SecAuthInitMsg, user_name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "group_name",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SecAuthInitMsg, group_name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cert_user_name",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SecAuthInitMsg, cert_user_name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cert_group_names",
    6,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(SecAuthInitMsg, n_cert_group_names),
    offsetof(SecAuthInitMsg, cert_group_names),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hostname",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SecAuthInitMsg, hostname),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ip",
    8,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SecAuthInitMsg, ip),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "auth_type",
    9,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(SecAuthInitMsg, auth_type),
    NULL,
    &sec_auth_init_msg__auth_type__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sec_auth_init_msg__field_indices_by_name[] = {
  7,   /* field[7] = auth_type */
  4,   /* field[4] = cert_group_names */
  3,   /* field[3] = cert_user_name */
  2,   /* field[2] = group_name */
  5,   /* field[5] = hostname */
  6,   /* field[6] = ip */
  0,   /* field[0] = tls_auth_ok */
  1,   /* field[1] = user_name */
};
static const ProtobufCIntRange sec_auth_init_msg__number_ranges[1 + 1] =
{
  { 2, 0 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor sec_auth_init_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "sec_auth_init_msg",
  "SecAuthInitMsg",
  "SecAuthInitMsg",
  "",
  sizeof(SecAuthInitMsg),
  8,
  sec_auth_init_msg__field_descriptors,
  sec_auth_init_msg__field_indices_by_name,
  1,  sec_auth_init_msg__number_ranges,
  (ProtobufCMessageInit) sec_auth_init_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sec_auth_cont_msg__field_descriptors[3] =
{
  {
    "password",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SecAuthContMsg, password),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sid",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(SecAuthContMsg, sid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ip",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SecAuthContMsg, ip),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sec_auth_cont_msg__field_indices_by_name[] = {
  2,   /* field[2] = ip */
  0,   /* field[0] = password */
  1,   /* field[1] = sid */
};
static const ProtobufCIntRange sec_auth_cont_msg__number_ranges[1 + 1] =
{
  { 2, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor sec_auth_cont_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "sec_auth_cont_msg",
  "SecAuthContMsg",
  "SecAuthContMsg",
  "",
  sizeof(SecAuthContMsg),
  3,
  sec_auth_cont_msg__field_descriptors,
  sec_auth_cont_msg__field_indices_by_name,
  1,  sec_auth_cont_msg__number_ranges,
  (ProtobufCMessageInit) sec_auth_cont_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sec_auth_reply_msg__field_descriptors[6] =
{
  {
    "reply",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(SecAuthReplyMsg, reply),
    &auth__rep__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cookie",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(SecAuthReplyMsg, has_cookie),
    offsetof(SecAuthReplyMsg, cookie),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "user_name",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SecAuthReplyMsg, user_name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "msg",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SecAuthReplyMsg, msg),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dtls_session_id",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(SecAuthReplyMsg, has_dtls_session_id),
    offsetof(SecAuthReplyMsg, dtls_session_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sid",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(SecAuthReplyMsg, has_sid),
    offsetof(SecAuthReplyMsg, sid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sec_auth_reply_msg__field_indices_by_name[] = {
  1,   /* field[1] = cookie */
  4,   /* field[4] = dtls_session_id */
  3,   /* field[3] = msg */
  0,   /* field[0] = reply */
  5,   /* field[5] = sid */
  2,   /* field[2] = user_name */
};
static const ProtobufCIntRange sec_auth_reply_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor sec_auth_reply_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "sec_auth_reply_msg",
  "SecAuthReplyMsg",
  "SecAuthReplyMsg",
  "",
  sizeof(SecAuthReplyMsg),
  6,
  sec_auth_reply_msg__field_descriptors,
  sec_auth_reply_msg__field_indices_by_name,
  1,  sec_auth_reply_msg__number_ranges,
  (ProtobufCMessageInit) sec_auth_reply_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sec_op_msg__field_descriptors[2] =
{
  {
    "key_idx",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(SecOpMsg, has_key_idx),
    offsetof(SecOpMsg, key_idx),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(SecOpMsg, data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sec_op_msg__field_indices_by_name[] = {
  1,   /* field[1] = data */
  0,   /* field[0] = key_idx */
};
static const ProtobufCIntRange sec_op_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor sec_op_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "sec_op_msg",
  "SecOpMsg",
  "SecOpMsg",
  "",
  sizeof(SecOpMsg),
  2,
  sec_op_msg__field_descriptors,
  sec_op_msg__field_indices_by_name,
  1,  sec_op_msg__number_ranges,
  (ProtobufCMessageInit) sec_op_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor cookie__field_descriptors[8] =
{
  {
    "username",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Cookie, username),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "groupname",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Cookie, groupname),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hostname",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Cookie, hostname),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ip",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Cookie, ip),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "expiration",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Cookie, expiration),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ipv4_seed",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Cookie, ipv4_seed),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sid",
    8,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Cookie, sid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tls_auth_ok",
    9,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Cookie, tls_auth_ok),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cookie__field_indices_by_name[] = {
  4,   /* field[4] = expiration */
  1,   /* field[1] = groupname */
  2,   /* field[2] = hostname */
  3,   /* field[3] = ip */
  5,   /* field[5] = ipv4_seed */
  6,   /* field[6] = sid */
  7,   /* field[7] = tls_auth_ok */
  0,   /* field[0] = username */
};
static const ProtobufCIntRange cookie__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 6, 4 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor cookie__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "cookie",
  "Cookie",
  "Cookie",
  "",
  sizeof(Cookie),
  8,
  cookie__field_descriptors,
  cookie__field_indices_by_name,
  2,  cookie__number_ranges,
  (ProtobufCMessageInit) cookie__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sec_auth_session_msg__field_descriptors[5] =
{
  {
    "sid",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(SecAuthSessionMsg, sid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cookie",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(SecAuthSessionMsg, has_cookie),
    offsetof(SecAuthSessionMsg, cookie),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "uptime",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(SecAuthSessionMsg, has_uptime),
    offsetof(SecAuthSessionMsg, uptime),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bytes_in",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(SecAuthSessionMsg, has_bytes_in),
    offsetof(SecAuthSessionMsg, bytes_in),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bytes_out",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(SecAuthSessionMsg, has_bytes_out),
    offsetof(SecAuthSessionMsg, bytes_out),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sec_auth_session_msg__field_indices_by_name[] = {
  3,   /* field[3] = bytes_in */
  4,   /* field[4] = bytes_out */
  1,   /* field[1] = cookie */
  0,   /* field[0] = sid */
  2,   /* field[2] = uptime */
};
static const ProtobufCIntRange sec_auth_session_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor sec_auth_session_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "sec_auth_session_msg",
  "SecAuthSessionMsg",
  "SecAuthSessionMsg",
  "",
  sizeof(SecAuthSessionMsg),
  5,
  sec_auth_session_msg__field_descriptors,
  sec_auth_session_msg__field_indices_by_name,
  1,  sec_auth_session_msg__number_ranges,
  (ProtobufCMessageInit) sec_auth_session_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sec_auth_session_reply_msg__field_descriptors[19] =
{
  {
    "reply",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(SecAuthSessionReplyMsg, reply),
    &auth__rep__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "no_udp",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(SecAuthSessionReplyMsg, has_no_udp),
    offsetof(SecAuthSessionReplyMsg, no_udp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "deny_roaming",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(SecAuthSessionReplyMsg, has_deny_roaming),
    offsetof(SecAuthSessionReplyMsg, deny_roaming),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "routes",
    13,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(SecAuthSessionReplyMsg, n_routes),
    offsetof(SecAuthSessionReplyMsg, routes),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "iroutes",
    14,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(SecAuthSessionReplyMsg, n_iroutes),
    offsetof(SecAuthSessionReplyMsg, iroutes),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dns",
    15,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(SecAuthSessionReplyMsg, n_dns),
    offsetof(SecAuthSessionReplyMsg, dns),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nbns",
    16,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(SecAuthSessionReplyMsg, n_nbns),
    offsetof(SecAuthSessionReplyMsg, nbns),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ipv4_net",
    17,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SecAuthSessionReplyMsg, ipv4_net),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ipv4_netmask",
    18,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SecAuthSessionReplyMsg, ipv4_netmask),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ipv6_net",
    19,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SecAuthSessionReplyMsg, ipv6_net),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ipv6_prefix",
    20,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(SecAuthSessionReplyMsg, has_ipv6_prefix),
    offsetof(SecAuthSessionReplyMsg, ipv6_prefix),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cgroup",
    21,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SecAuthSessionReplyMsg, cgroup),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "xml_config_file",
    22,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SecAuthSessionReplyMsg, xml_config_file),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rx_per_sec",
    23,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(SecAuthSessionReplyMsg, has_rx_per_sec),
    offsetof(SecAuthSessionReplyMsg, rx_per_sec),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tx_per_sec",
    24,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(SecAuthSessionReplyMsg, has_tx_per_sec),
    offsetof(SecAuthSessionReplyMsg, tx_per_sec),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "net_priority",
    25,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(SecAuthSessionReplyMsg, has_net_priority),
    offsetof(SecAuthSessionReplyMsg, net_priority),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "explicit_ipv4",
    26,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SecAuthSessionReplyMsg, explicit_ipv4),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "explicit_ipv6",
    27,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SecAuthSessionReplyMsg, explicit_ipv6),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "no_routes",
    28,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(SecAuthSessionReplyMsg, n_no_routes),
    offsetof(SecAuthSessionReplyMsg, no_routes),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sec_auth_session_reply_msg__field_indices_by_name[] = {
  11,   /* field[11] = cgroup */
  2,   /* field[2] = deny_roaming */
  5,   /* field[5] = dns */
  16,   /* field[16] = explicit_ipv4 */
  17,   /* field[17] = explicit_ipv6 */
  7,   /* field[7] = ipv4_net */
  8,   /* field[8] = ipv4_netmask */
  9,   /* field[9] = ipv6_net */
  10,   /* field[10] = ipv6_prefix */
  4,   /* field[4] = iroutes */
  6,   /* field[6] = nbns */
  15,   /* field[15] = net_priority */
  18,   /* field[18] = no_routes */
  1,   /* field[1] = no_udp */
  0,   /* field[0] = reply */
  3,   /* field[3] = routes */
  13,   /* field[13] = rx_per_sec */
  14,   /* field[14] = tx_per_sec */
  12,   /* field[12] = xml_config_file */
};
static const ProtobufCIntRange sec_auth_session_reply_msg__number_ranges[3 + 1] =
{
  { 1, 0 },
  { 10, 1 },
  { 13, 3 },
  { 0, 19 }
};
const ProtobufCMessageDescriptor sec_auth_session_reply_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "sec_auth_session_reply_msg",
  "SecAuthSessionReplyMsg",
  "SecAuthSessionReplyMsg",
  "",
  sizeof(SecAuthSessionReplyMsg),
  19,
  sec_auth_session_reply_msg__field_descriptors,
  sec_auth_session_reply_msg__field_indices_by_name,
  3,  sec_auth_session_reply_msg__number_ranges,
  (ProtobufCMessageInit) sec_auth_session_reply_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
const ProtobufCEnumValue auth__rep__enum_values_by_number[3] =
{
  { "OK", "AUTH__REP__OK", 1 },
  { "MSG", "AUTH__REP__MSG", 2 },
  { "FAILED", "AUTH__REP__FAILED", 3 },
};
static const ProtobufCIntRange auth__rep__value_ranges[] = {
{1, 0},{0, 3}
};
const ProtobufCEnumValueIndex auth__rep__enum_values_by_name[3] =
{
  { "FAILED", 2 },
  { "MSG", 1 },
  { "OK", 0 },
};
const ProtobufCEnumDescriptor auth__rep__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "AUTH_REP",
  "AUTH_REP",
  "AUTHREP",
  "",
  3,
  auth__rep__enum_values_by_number,
  3,
  auth__rep__enum_values_by_name,
  1,
  auth__rep__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
